import { execFileSync } from "node:child_process";

/**
 * Synthetic videos with KNOWN ground truth, generated by ffmpeg's lavfi
 * sources — so the analyzer's tests need no checked-in media and no
 * network, and every expected number is one we constructed rather than
 * eyeballed. Each builder returns the truth alongside the file.
 */

const SIZE = "360x640";
const FPS = 30;

const ffmpeg = (args: string[]): void => {
  execFileSync("ffmpeg", ["-y", "-v", "error", ...args], { stdio: ["ignore", "ignore", "inherit"] });
};

/** A click every `periodSec`, `clickSec` long, 1 kHz — the cleanest possible
 *  beat. Silent otherwise. */
const clickTrack = (durationSec: number, periodSec: number): string[] => [
  "-f",
  "lavfi",
  "-i",
  `aevalsrc='sin(2*PI*1000*t)*lt(mod(t,${periodSec}),0.03)':s=16000:d=${durationSec}`,
];

/** Four unrelated 2 s pictures back to back: 3 hard cuts at 2, 4, 6 s. */
export const makeHardCutVideo = (outPath: string): { cutTimesSec: number[]; durationSec: number } => {
  const sources = ["testsrc2", "smptebars", "mandelbrot", "rgbtestsrc"];
  const inputs = sources.flatMap((s) => ["-f", "lavfi", "-t", "2", "-i", `${s}=size=${SIZE}:rate=${FPS}`]);
  ffmpeg([
    ...inputs,
    "-filter_complex",
    `${sources.map((_, i) => `[${i}:v]format=yuv420p,setsar=1[v${i}]`).join(";")};${sources.map((_, i) => `[v${i}]`).join("")}concat=n=${sources.length}:v=1:a=0[v]`,
    "-map",
    "[v]",
    "-pix_fmt",
    "yuv420p",
    "-r",
    String(FPS),
    outPath,
  ]);
  return { cutTimesSec: [2, 4, 6], durationSec: 8 };
};

/** ONE continuous take with a same-take punch-in: normal 0-2.5 s, magnified
 *  1.3x 2.5-5 s, normal again 5-8 s. Scene detection sees no cut here (it is
 *  the same picture); only the zoom fit does. */
export const makePunchInVideo = (
  outPath: string,
): { punchInAtSec: number; punchOutAtSec: number; scale: number; durationSec: number } => {
  const scale = 1.3;
  ffmpeg([
    "-f",
    "lavfi",
    "-t",
    "8",
    "-i",
    `testsrc2=size=${SIZE}:rate=${FPS}`,
    "-filter_complex",
    `[0:v]split=3[a][b][c];` +
      `[a]trim=0:2.5,setpts=PTS-STARTPTS,setsar=1[a1];` +
      `[b]trim=2.5:5,setpts=PTS-STARTPTS,crop=iw/${scale}:ih/${scale},scale=${SIZE.replace("x", ":")},setsar=1[b1];` +
      `[c]trim=5:8,setpts=PTS-STARTPTS,setsar=1[c1];` +
      `[a1][b1][c1]concat=n=3:v=1:a=0[v]`,
    "-map",
    "[v]",
    "-pix_fmt",
    "yuv420p",
    "-r",
    String(FPS),
    outPath,
  ]);
  return { punchInAtSec: 2.5, punchOutAtSec: 5, scale, durationSec: 8 };
};

/** A static picture with a 120 BPM click track — no cuts, a known tempo. */
export const makeBeatVideo = (outPath: string, bpm = 120, durationSec = 12): { bpm: number; durationSec: number } => {
  ffmpeg([
    "-f",
    "lavfi",
    "-t",
    String(durationSec),
    "-i",
    `color=c=0x336699:size=${SIZE}:rate=${FPS}`,
    ...clickTrack(durationSec, 60 / bpm),
    "-map",
    "0:v",
    "-map",
    "1:a",
    "-c:v",
    "libx264",
    "-pix_fmt",
    "yuv420p",
    "-c:a",
    "aac",
    "-shortest",
    outPath,
  ]);
  return { bpm, durationSec };
};

/** A camera that shakes: a texture that is equally detailed EVERYWHERE
 *  (so every 4x4 block sees the same motion when the whole frame moves),
 *  cropped through a window whose origin wobbles every frame. testsrc2 is
 *  the wrong picture for this — it has flat regions that show no motion
 *  under a shake, which would read as "only some blocks moved". */
export const makeShakeVideo = (outPath: string): void => {
  ffmpeg([
    "-f",
    "lavfi",
    "-t",
    "6",
    "-i",
    `nullsrc=size=400x680:rate=${FPS},geq=lum='128+60*sin(X/3)*cos(Y/4)+60*sin((X+Y)/5)':cb=128:cr=128`,
    "-vf",
    `crop=360:640:20+18*sin(n*2.7):20+18*cos(n*3.1)`,
    "-pix_fmt",
    "yuv420p",
    outPath,
  ]);
};

/** A locked-off frame with a single small moving box: subject motion only. */
export const makeSubjectVideo = (outPath: string): void => {
  ffmpeg([
    "-f",
    "lavfi",
    "-t",
    "6",
    "-i",
    `nullsrc=size=${SIZE}:rate=${FPS},geq=lum='128+60*sin(X/3)*cos(Y/4)+60*sin((X+Y)/5)':cb=128:cr=128`,
    "-f",
    "lavfi",
    "-t",
    "6",
    "-i",
    `color=c=white:size=80x80:rate=${FPS}`,
    "-filter_complex",
    `[0:v][1:v]overlay=x='40+180*abs(sin(t*3))':y=300[v]`,
    "-map",
    "[v]",
    "-pix_fmt",
    "yuv420p",
    outPath,
  ]);
};
